# 공식 Python 이미지 사용
# Debian Linux 기반 이미지이며 경량 버전임
# 해당 이미지에는 HTTP 서버가 내장되어있음
FROM python:3.14-slim

# 디렉토리 설정
# 컨테이너 내부에 '/app' 디렉토리를 생성
# 이후 'server.py' 파일을 해당 디렉토리에 복사
WORKDIR /app
COPY server.py /app/

# 환경변수 설정
# 'server.py' 에서 이 값을 사용
ENV PORT=8080
ENV USE_TLS=false

# 사용하는 포트를 명시
EXPOSE 8080

# 컨테이너 시작시 실행할 명령어
# 'server.py' 를 바로 실행함
CMD ["python", "server.py"]